### ISSUE TITLE
DSDL compiler: use of undeclared identifier in generated code

### ISSUE THREAD

**Issue by adolfogc** [UAVCAN/libcanard#88]
https://github.com/UAVCAN/libcanard/blob/16e4f34341f510c0ddde13a8d5a203c7ffb156f2/dsdl_compiler/libcanard_dsdl_compiler/code_type_template.tmpl#L320

A bug was introduced in PR #86. The identifier `transfer_len` is undeclared at this scope, the correct one seems to be `payload_len`, as discussed in #83.

**Comment by aasmune** [comment]
My bad, will fix it!
